### PR TITLE
Upgraded csproj to SDK style

### PR DESCRIPTION
**Pull request by dougbenham**
#69 #77 

References for why its a good change:

- https://learn.microsoft.com/en-us/dotnet/core/project-sdk/overview
- https://stackoverflow.com/questions/68083511/is-sdk-style-project-the-recommended-approach-for-new-net-framework-projects
- https://learn.microsoft.com/en-us/dotnet/core/porting/#considerations-when-porting

Also if you look at the csproj before and after, I think its much simpler and preferable.

### CODE REVIEW

**Comment by Vectorial1024** [comment]
I didn't know there is this new project file format, but I have been thinking about changing some of the dll references to use nuget anyways instead of pointing to the mod directory.

Over the years as I changed my computer several times, since the folder structure etc changed as I changed my computer, the project config file just had to be updated. And then this looks bad in the commit history.

Quick read from your links show that the SDK format is most probably for NET framework 5+, so I do need to confirm whether RimWorld's 47.2 is suitable for this. But still yes, the new format is much cleaner.

**Comment by dougbenham** [comment]
> I didn't know there is this new project file format, but I have been thinking about changing some of the dll references to use nuget anyways instead of pointing to the mod directory.
> 
> Over the years as I changed my computer several times, since the folder structure etc changed as I changed my computer, the project config file just had to be updated. And then this looks bad in the commit history.
> 
> Quick read from your links show that the SDK format is most probably for NET framework 5+, so I do need to confirm whether RimWorld's 47.2 is suitable for this. But still yes, the new format is much cleaner.

There's no such thing as .NET Framework 5. And yes .NET Framework 4.7.2 is compatible and encouraged by microsoft to use this new SDK style project format as seen in that second reference (stackoverflow) link. But yea feel free to do your own research too, no rush.

**Comment by Vectorial1024** [comment]
I actually played around with this locally just now, and I noticed it producing the DLL one level deeper, so to speak; now the DLLs appear in `/v1.5/Assemblies/net472/[DLL]`

Would need to research whether I can somehow force it to put it back to `/v1.5/Assemblies/[DLL]`; but other than that, it is a good progress.

**Comment by dougbenham** [comment]
> I actually played around with this locally just now, and I noticed it producing the DLL one level deeper, so to speak; now the DLLs appear in `/v1.5/Assemblies/net472/[DLL]`
> 
> Would need to research whether I can somehow force it to put it back to `/v1.5/Assemblies/[DLL]`; but other than that, it is a good progress.

It should not do that as long as you have the `<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>` line in your csproj.

**Comment by Vectorial1024** [comment]
aight let's do this

**Comment by Vectorial1024** [comment]
The release will come out in the weekend, to give a few days and see which other mods are updated.

**Comment by Vectorial1024** [comment]
Unfortunately I have to revert to use the assembly references for Harmony and HugsLib; it seems I cannot refuse their appearance in the build destination when using their nuget version, which makes sense but adds to the mod size significantly (Harmony being larger than the entire mod is quite problematic),

**Comment by dougbenham** [comment]
> Unfortunately I have to revert to use the assembly references for Harmony and HugsLib; it seems I cannot refuse their appearance in the build destination when using their nuget version, which makes sense but adds to the mod size significantly (Harmony being larger than the entire mod is quite problematic),

Any reason why you can't delete those dlls before publishing the mod? There's no need to include harmony in your final published files.

**Comment by Vectorial1024** [comment]
That'd be too tedious.

Might as well do dll reference + "copy local = false" and call it a day, so that I can do something else with ease of mind.

**Comment by dougbenham** [comment]
> That'd be too tedious.
> 
> Might as well do dll reference + "copy local = false" and call it a day, so that I can do something else with ease of mind.

I did a little googling and found out you can do something like this

```
    <PackageReference Include="log4net" Version="2.0.8">
        <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
```

ExcludeAssets prevents dlls from being copied to the output. Anyways no worries if you don't want to do it, I know you spent a bit of time on this minor task already anyways.

**Comment by Vectorial1024** [comment]
I also scrolled past this https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files but then 
at a quick read could not understand what is `ExcludeAssets`

This approach is quite different from the old method... at this point in the years I am not sure how to use Google now. I don't even know anymore how to ask it to give me "do not put this in" but not "help I can't put this in"...

I'm gonna try that.

**Comment by Vectorial1024** [comment]
Readopted via 92be70c6323588a32e16d41ae34d1a8e7fa3dbc2

**Comment by dougbenham** [comment]
Thanks for your patience.

**Pull request merged**
