### PR TITLE
Fixed moody transpiler patch

### PR DESCRIPTION
**Pull request by dougbenham**

### CODE REVIEW

**Comment by dougbenham** [comment]
Any reason why this wasn't applied in the 1.5 update? Its still broken.

**Comment by Vectorial1024** [comment]
Did you notice how this PR sat here for so many weeks with no approval/rejection? Why would I leave this open if I have implemented the changes? Why are you confused that your PR is not in the public release?

Answer: I haven't done this yet.

Info: I was too busy irl to deal with this. When I finally returned, 1.5 was set to release very soon, so no use working on EBF until 1.5 was released.

I would say you were simply asking too early. I will be working on these backlog items very soon, but you were simply too early.

**Comment by dougbenham** [comment]
No need for hostility, I apologize if my question came across negatively.

**Comment by Vectorial1024** [comment]
It's OK; it doesn't help that this PR is way overdue, and then I really had too much stuff going on irl.

You will still get the credit seeing that you found out about this when I was unavailable.

**Review by Vectorial1024 — APPROVED** [review]

**Pull request merged**
